
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: notigenie:dev
    # "./src"をコンテナ内の"/app"にマウントする
    # これにより、ローカルでのコード変更が即座にコンテナに反映される
    volumes:
      - ./src:/app
      # 設定ファイルは個別にマウントすることで、ソースコードとは独立して管理し、
      # 環境ごとの設定変更を容易にする。
      - ./src/config.yaml:/app/config.yaml
    # .envファイルの内容を環境変数としてコンテナに読み込む
    env_file:
      - .env
    # コンテナを起動し続けるための設定
    # tty: trueは、コンテナの標準入力を開き続けるために必要
    tty: true
    environment:
      - PYTHONIOENCODING=UTF-8
